### ISSUE TITLE
jasmine_chromeapp failing to start when run with other tests

### ISSUE THREAD

**Issue by dborkan** [freedomjs/freedom-social-xmpp#87]
In the latest freedom-social-xmpp, jasmine_chromeapp tests are able to run fine when they are run standalone with "grunt jasmine_chromeapp" (the tests might fail occasionally if those accounts are "in jail" for sending too many messages, but at least the tests run).

However, if we add jasmine_chromeapp to the end of the 'test' rule, then run "grunt test", we get this error:
```
Running "jasmine_chromeapp:all" (jasmine_chromeapp) task 
Building...Done. 
Checking / Installing Selenium...Fatal error: Cannot call method 'expect' of null
```

**Comment by willscott** [comment]
This should be fixed in the latest version of jasmine_chromeapp
