### ISSUE TITLE
Only get VCard / images for online users

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom-social-xmpp#91]
Currently when we log in for the first time, it gets stuck not seeing other users until the browser is restarted. I suspect it may have to do with the initial caching of the roster.

**Comment by dborkan** [comment]
+1, also uProxy completely ignores ONLINE_WITH_OTHER_APP clients now, and
we can use stored images in uProxy for any users who were previously ONLINE
with uProxy but are now OFFLINE.

**Comment by iislucas** [comment]
Different users might want different caching behaviours... What do you think of removing caching from social-xmpp and letting the consumer do caching in the way they want to?

**Comment by willscott** [comment]
no clue what that would look like from an interface perspective. I think it's easy to defer picture gather for anyone who isn't "ONLINE". that seems like the short-term solution.

**Comment by iislucas** [comment]
Not caching wouldn't look any different in terms of interface. Caching is not exposed in the interface. Are you thinking of having cache behaviour in the interface? I guess you could do it in setup with a 'cache' param that can be 'cacheNone', 'cacheOnline', 'cacheOnlineAndOnLineWithOtherApp', 'cacheAll'.

**Comment by ryscheng** [comment]
This issue has nothing to do with caching. We currently retrieve images for
every buddy (online or offline). This makes the first time you log in
painful. We are just proposing that we change the behavior to only retrieve
images for ONLINE users.

**Comment by iislucas** [comment]
good point; one might separate the problem caching it all vs even bothering to download it. So I guess what we're really thinking about specifying is an argument to getRoster which can be 'online', 'onlineAndOnLineWithOtherApp', 'all' ?

**Comment by ryscheng** [comment]
The scope of this issue doesn't pertain to changes in the interface either.
It's just to change the current implicit behavior.

**Comment by iislucas** [comment]
Changing interface seems like a natural extension of this issue and way to tackle this problem more generally, so I think this is the right place to start discussing it. But I agree, if it's not a dumb idea, then we should file it as a separate issue.

**Comment by ryscheng** [comment]
https://github.com/freedomjs/freedom-social-xmpp/pull/98
