### ISSUE TITLE
Batching uses JSON.parse

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom-social-xmpp#97]
causes errors when receiving messages from non-uProxy clients.
We should only batch between 2 users that are ONLINE

**Comment by iislucas** [comment]
And we should have a try-catch wrapper around the JSON.parse (to stop a malicious user-agent being able to kill the freedom module)

**Comment by ryscheng** [comment]
https://github.com/freedomjs/freedom-social-xmpp/pull/99
